### PR TITLE
Adds support for x86 Windows 7 images

### PR DESCRIPTION
**Pull request by lehuff**
--win7 now properly works for x86 versions of windows and --win7x64 works for x64 versions.

Split Windows into two classes and slightly modified the xml file to accept the arch change between the two classes.

### CODE REVIEW

**Comment by lehuff** [comment]
I updated this pull with a small fix for 16 character hostnames causing the unattended install to bomb out.  Here's a link that has a similar error to what I was getting:

https://social.technet.microsoft.com/Forums/en-US/9036aaee-b888-4492-8b2b-a2c80ea3a69d/osd-fails-on-apply-windows-settings-with-return-code-0x80220005?forum=configmgrgeneral

**Comment by jbremer** [comment]
Sweet! Thanks :)

**Comment by jbremer** [comment]
I'll do a quick test this week and push a new release afterwards, thanks again!

**Comment by lehuff** [comment]
No problem!  Only thing I've noticed in testing is that the .NET 4 install (vmcloak-install) is 64bit. Depending on how much you care it may be worth it to add the 32bit version into that as well, everything else installs perfectly.

**Comment by jbremer** [comment]
```bash
$ file dotNetFx40_Full_x86_x64.exe
dotNetFx40_Full_x86_x64.exe: PE32 executable (GUI) Intel 80386, for MS Windows
```

The filename implies it should also work on x86. I believe the `wic` may have to be installed first, though (or at least that was the case on winxp) - could you please check that?

**Comment by lehuff** [comment]
You are correct, it works fine on x86, it must have just bombed out on me the first time 'because windows'.

**Comment by jbremer** [comment]
Oke, thanks again!

**Pull request merged**
