### PR TITLE
Improvements to dependencies

### PR DESCRIPTION
**Pull request by tweemeterjop**
- One can now use the --vrde flag in vmcloak to enable the VirtualBox Remote Desktop Extension (VRDE) option in VirtualBox. This can be used to monitor the progress in the VM or to make modifications when running vmcloak modify.
- Allow multiple urls per dependency. Try the official url (if available) first and use the cuckoo.sh as a backup link.
- Rewrote the downloader to stop using a syscall to wget. Now using urllib2.
- Added support for Adobe Reader newer than version 11.0.11. These use a MSI update/patch package.
- Added more versions to vceredist and dotnet framework.
- Added support for a "latest" version, if there is a (dynamic) direct link to the latest version.

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
About Chrome: http://stackoverflow.com/a/31939624 suggests to just take away Chrome's update program. Shouldn't be too bad since the stuff in VMs is not being used by humans, only bots.

**Comment by tweemeterjop** [comment]
Some progress:

- Support for interactive snapshot creation mode (--interactive)
When creating a snapshot vmcloak changes the hostname and mac address. This might trigger the windows or MS office activation. So when you run the snapshot creation in interactive mode, we spawn a notepad and wait for it to close. This gives you some time right before taking the snapshot to activate your products.

- Added a lot of "official" URLs for dependencies (dotnet/java/vcredist)
Use the cuckoo.sh urls as a backup option.

- VRDE improvements
VRDE is now enabled when you use the --debug flag. You can specify a different port with --vrde-port.

- Weaken the security of IE11
skip first run, disable protected view for all zones etc

- Weaken Flash security
Use a configuration file and disable protected mode.

- Weaken Java security
We now use a java deployment file to configure the java settings globally and lock the settings. This now disables the sandbox mode and disables certificate checks etc. The default security mode is MEDIUM (lowest).

- Added newer versions of Python, Pillow, wic, silverlight, vcredist

- Choose the dependency architecture
One can now also specify the target architecture of the dependency. This allows installing a 32bit executable on a 64bit host. Example: vmcloak install <vmname> java java.version=7u40 java.arch=x86

**Comment by MarkusTeufelberger** [comment]
Lots of useful stuff in here, do you still work on this or could/should it get merged?

**Comment by tweemeterjop** [comment]
bump

**Comment by jbremer** [comment]
Thanks a lot, once again! All's been merged now.

**Pull request merged**
