### PR TITLE
Update vmcloak-vboxnet0

### PR DESCRIPTION
**Pull request by doomedraven**
option to specify other host ip, can be very useful

### CODE REVIEW

**Comment by jbremer** [comment]
Thanks! Do you have any special IP addresses / ranges that you use? :-)

**Comment by doomedraven** [comment]
different of x.x.56.x, and is can be useful to use it passing params, to quick deploy and if params not passed usign default params with x.x.56.x :)

**Comment by jbremer** [comment]
Sure of course :)

**Comment by doomedraven** [comment]
@jbremer Thanks for merg it :) now i can use it from repo, without change it

**Comment by jbremer** [comment]
Of course, no problem! Sorry for the delay :)

**Pull request merged**
